[project]
name = "kennel"
revision = "1.0"

[providers]
local = "dotenv://.env"
openbao = "openbao://secrets.scottylabs.org/secret"
openbao-ci = "openbao://secrets.scottylabs.org/secret?auth=jwt&role=ci&audience=openbao"

[profiles.default]
AWS_ACCESS_KEY_ID = { description = "sccache S3 access key ID", ref = { item = "shared/sccache", field = "AWS_ACCESS_KEY_ID" } }
AWS_SECRET_ACCESS_KEY = { description = "sccache S3 secret access key", ref = { item = "shared/sccache", field = "AWS_SECRET_ACCESS_KEY" } }
CACHIX_AUTH_TOKEN = { description = "Cachix auth token", ref = { item = "shared/cachix", field = "CACHIX_AUTH_TOKEN" } }

[profiles.dev.defaults]
providers = ["openbao"]

[profiles.dev]

[profiles.ci.defaults]
providers = ["openbao-ci"]

[profiles.ci]
