[package]
name = "kennel-deployer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.102"
entity = { version = "0.1.0", path = "../entity" }
kennel-builder = { version = "0.1.0", path = "../kennel-builder" }
kennel-config = { version = "0.1.0", path = "../kennel-config" }
kennel-dns = { version = "0.1.0", path = "../kennel-dns" }
kennel-provision = { version = "0.1.0", path = "../kennel-provision" }
kennel-router = { version = "0.1.0", path = "../kennel-router" }
kennel-secrets = { version = "0.1.0", path = "../kennel-secrets" }
kennel-store = { version = "0.1.0", path = "../kennel-store" }
kennel-supervisor = { version = "0.1.0", path = "../kennel-supervisor" }
reqwest = "0.13.2"
sea-orm = "1.1.19"
serde_json = "1.0.149"
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = ["full"] }
tracing = "0.1.44"
