[package]
name = "kennel-deployer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
entity = { version = "0.1.0", path = "../entity" }
kennel-config = { version = "0.1.0", path = "../kennel-config" }
kennel-dns = { version = "0.1.0", path = "../kennel-dns" }
kennel-provision = { version = "0.1.0", path = "../kennel-provision" }
kennel-store = { version = "0.1.0", path = "../kennel-store" }
kennel-supervisor = { version = "0.1.0", path = "../kennel-supervisor" }
reqwest.workspace = true
sea-orm.workspace = true
secrecy = "0.10.3"
secretspec = { version = "0.8.0", features = ["vault"] }
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
uuid = "1.23.0"
