name: CI
on:
  push:
    branches: [main, staging, dev]
  pull_request:

jobs:
  check:
    runs-on: docker
    env:
      NIX_CONFIG: sandbox = true
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4

      - name: Install Nix
        uses: https://github.com/cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            extra-substituters = https://scottylabs.cachix.org
            extra-trusted-public-keys = scottylabs.cachix.org-1:hajjEX5SLi/Y7yYloiXTt2IOr3towcTGRhMh1vu6Tjg=

      - name: Install devenv
        run: nix profile add nixpkgs#devenv

      - name: Check formatting
        run: devenv shell treefmt --fail-on-change

      - name: Clippy
        run: devenv shell cargo clippy -- -D warnings

      - name: Test
        run: devenv shell cargo test

      - name: Verify Cargo.nix is up to date
        shell: devenv shell bash -- -e {0}
        run: |
          crate2nix generate
          git diff --exit-code Cargo.nix

      - name: Build
        run: nix build
