name: CI

on:
  push:
    branches: [main, staging, dev]
  pull_request:

jobs:
  check:
    uses: https://git.cmu.dev/ScottyLabs/kennel/.forgejo/workflows/ci.yml@main
    enable-openid-connect: true
