//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::BuildStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "builds")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub project_name: String,
    #[sea_orm(column_type = "Text")]
    pub branch: String,
    #[sea_orm(column_type = "Text")]
    pub git_ref: String,
    #[sea_orm(column_type = "Text")]
    pub commit_sha: String,
    pub status: BuildStatus,
    pub started_at: Option<DateTime>,
    pub finished_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::build_results::Entity")]
    BuildResults,
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::ProjectName",
        to = "super::projects::Column::Name",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Projects,
}

impl Related<super::build_results::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BuildResults.def()
    }
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
