//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::DeploymentStatus;
use super::sea_orm_active_enums::DnsStatus;
use super::sea_orm_active_enums::Environment;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "deployments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub project_name: String,
    #[sea_orm(column_type = "Text")]
    pub service_name: String,
    #[sea_orm(column_type = "Text")]
    pub branch: String,
    #[sea_orm(column_type = "Text")]
    pub branch_slug: String,
    pub environment: Environment,
    #[sea_orm(column_type = "Text")]
    pub git_ref: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub store_path: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub process_config: Option<Json>,
    pub status: DeploymentStatus,
    #[sea_orm(column_type = "Text")]
    pub domain: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub process_name: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub last_activity: DateTime,
    pub dns_status: DnsStatus,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::dns_records::Entity")]
    DnsRecords,
    #[sea_orm(
        belongs_to = "super::services::Entity",
        from = "(Column::ProjectName, Column::ServiceName)",
        to = "(super::services::Column::ProjectName, super::services::Column::Name)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Services,
}

impl Related<super::dns_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DnsRecords.def()
    }
}

impl Related<super::services::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Services.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
