//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "port_allocations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub port: i32,
    pub deployment_id: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub project_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub service_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub branch: Option<String>,
    pub allocated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::deployments::Entity",
        from = "Column::DeploymentId",
        to = "super::deployments::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Deployments,
}

impl Related<super::deployments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Deployments.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
