//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    utoipa :: ToSchema,
)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "build_result_status"
)]
pub enum BuildResultStatus {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "building")]
    Building,
    #[sea_orm(string_value = "success")]
    Success,
    #[sea_orm(string_value = "skipped")]
    Skipped,
    #[sea_orm(string_value = "failed")]
    Failed,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    utoipa :: ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "build_status")]
pub enum BuildStatus {
    #[sea_orm(string_value = "queued")]
    Queued,
    #[sea_orm(string_value = "building")]
    Building,
    #[sea_orm(string_value = "success")]
    Success,
    #[sea_orm(string_value = "failed")]
    Failed,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    utoipa :: ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "deployment_status")]
pub enum DeploymentStatus {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "building")]
    Building,
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "failed")]
    Failed,
    #[sea_orm(string_value = "tearing_down")]
    TearingDown,
    #[sea_orm(string_value = "torn_down")]
    TornDown,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    utoipa :: ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "repo_type")]
pub enum RepoType {
    #[sea_orm(string_value = "forgejo")]
    Forgejo,
    #[sea_orm(string_value = "github")]
    Github,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    utoipa :: ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "service_type")]
pub enum ServiceType {
    #[sea_orm(string_value = "service")]
    Service,
    #[sea_orm(string_value = "static")]
    Static,
    #[sea_orm(string_value = "image")]
    Image,
}
