//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::ServiceType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "services")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub project_name: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub r#type: ServiceType,
    #[sea_orm(column_type = "Text")]
    pub package: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub health_check: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub custom_domain: Option<String>,
    pub spa: bool,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::deployments::Entity")]
    Deployments,
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::ProjectName",
        to = "super::projects::Column::Name",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Projects,
}

impl Related<super::deployments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Deployments.def()
    }
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
