[package]
name = "kennel-builder"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
entity = { version = "0.1.0", path = "../entity" }
kennel-config = { version = "0.1.0", path = "../kennel-config" }
kennel-store = { version = "0.1.0", path = "../kennel-store" }
kennel-supervisor = { version = "0.1.0", path = "../kennel-supervisor" }
sea-orm.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
uuid = "1.23.0"

[dev-dependencies]
tempfile = "3.26.0"
